type FilmsCollection {
    items: [Film]!
    total: Int!
}

type Film @cacheControl(maxAge: 86400){
  title: String!
  episode_id: String!
  opening_crawl: String!
  director: String!
  producer: String!
  release_date: String!
  characters: [String]!
  planets: [Planet]!
  planetsUrl: [String]!
  starships: [Starship]!
  starshipsUrl: [String]!
  vehicles: [Vehicle]!
  vehiclesUrl: [String]!
  species: [Specie]!
  speciesUrl: [String]!
  created: String!
  edited: String!
  url: String!
}