enum CacheControlScope {
    PUBLIC
    PRIVATE
  }

directive @cacheControl(
    maxAge: Int
    scope: CacheControlScope
    inheritMaxAge: Boolean
  ) on FIELD_DEFINITION | OBJECT | INTERFACE | UNION

type SpeciesCollection {
  items: [Specie]!
  total: Int!
}

type Film @cacheControl(maxAge: 86400){
  title: String!
  episode_id: String!
  opening_crawl: String!
  director: String!
  producer: String!
  release_date: String!
  characters: [String]!
  planets: [Planet]!
  planetsUrl: [String]!
  starships: [Starship]!
  starshipsUrl: [String]!
  vehicles: [Vehicle]!
  vehiclesUrl: [String]!
  species: [Specie]!
  speciesUrl: [String]!
  created: String!
  edited: String!
  url: String!
}

type Specie @cacheControl(maxAge: 86400){
  name: String!
  classification: String!
  designation: String!
  average_height: String!
  skin_colors: String!
  eye_colors: String!
  hair_colors: String!
  homeworld: String
  language: String!
  people: [String]!
  films: [Film]!
  filmsUrl: [String]!
  created: String!
  edited: String!
  url: String!
}

type FilmsCollection {
    items: [Film]!
    total: Int!
}

type VehiclesCollection {
    items: [Vehicle]!
    total: Int!
}

type Vehicle @cacheControl(maxAge: 86400) {
  name: String!
  model: String!
  vehicle_class: String!
  manufacturer: String!
  length: String!
  cost_in_credits: String!
  crew: String!
  passengers: String!
  max_atmosphering_speed: String!
  cargo_capacity: String!
  consumables: String
  films: [Film]!
  filmsUrl: [String]!
  pilots: [String!]!
  url: String!
  created: String!
  edited: String!
}

type StarshipsCollection {
    items: [Starship]!
    total: Int!
}

type Starship @cacheControl(maxAge: 10){
  name: String!
  model: String!
  starship_class: String!
  manufacturer: String!
  cost_in_credits: String!
  length: String!
  crew: String!
  passengers: String!
  max_atmosphering_speed: String!
  hyperdrive_rating: String!
  MGLT: String!
  cargo_capacity: String!
  consumables: String
  filmsUrl: [String!]
  films: [Film]
  pilots: [String!]!
  url: String!
  created: String!
  edited: String!
}

type PlanetsCollection {
    items: [Planet]!
    total: Int!
}

type Planet @cacheControl(maxAge: 86400){
  name: String!
  diameter: String!
  rotation_period: String!
  orbital_period: String!
  gravity: String!
  population: String!
  climate: String!
  terrain: String!
  surface_water: String!
  residents: [String!]!
  films: [Film]!
  filmsUrl: [String]!
  url: String!
  created: String!
  edited: String!
}

type UniqueWords @cacheControl(maxAge: 10) {
 word: String!
 count: Int!
}


type UniqueWordsCollection {
 items: [UniqueWords]!
 total: Int!
}

type MostCommonName @cacheControl(maxAge: 10) {
  names: [String]!
}


type Query {
  """
  Returns all films.
  """
  getFilms(filter: String, page: Int): FilmsCollection @cacheControl(maxAge: 86400)
  """
  Returns all species.
  """
  getSpecies(filter: String, page: Int): SpeciesCollection @cacheControl(maxAge: 86400)
  """
  Returns all vehicles.
  """
  getVehicles(filter: String, page: Int): VehiclesCollection @cacheControl(maxAge: 86400)
  """
  Returns all starships.
  """
  getStarships(filter: String, page: Int): StarshipsCollection @cacheControl(maxAge: 10)
  """
  Returns all planets.
  """
  getPlanets(filter: String, page: Int): PlanetsCollection @cacheControl(maxAge: 86400)
  """
  Returns film of provided id.
  """
  getFilm(id: String!): Film @cacheControl(maxAge: 86400)
  """
  Returns specie of provided id.
  """
  getSpecie(id: String!): Specie @cacheControl(maxAge: 86400)
  """
  Returns vehicle of provided id.
  """
  getVehicle(id: String!): Vehicle @cacheControl(maxAge: 86400)
  """
  Returns starship of provided id.
  """
  getStarship(id: String!): Starship @cacheControl(maxAge: 86400)
  """
  Returns planet of provided id.
  """
  getPlanet(id: String!): Planet @cacheControl(maxAge: 86400)
  """
  Returns an array of unique words from all films opening_crawls, paired with their occurences.
  """
  getUniqueWords: UniqueWordsCollection @cacheControl(maxAge: 10)
  """
  Returns an array of most common name or names from opening_crawls.
  """
  getMostCommonName: MostCommonName @cacheControl(maxAge: 10)
}