# import * from './parts/film.gql'

enum CacheControlScope {
    PUBLIC
    PRIVATE
  }

directive @cacheControl(
    maxAge: Int
    scope: CacheControlScope
    inheritMaxAge: Boolean
  ) on FIELD_DEFINITION | OBJECT | INTERFACE | UNION

type FilmsCollection {
    items: [Film]!
    total: Int!
}

type Film {
  title: String!
  episode_id: String!
  opening_crawl: String!
  director: String!
  producer: String!
  release_date: String!
  characters: [String]!
  planets: [String]!
  starships: [String]!
  vehicles: [String]!
  species: [String]!
  created: String!
  edited: String!
  url: String!
}

type Query {
  """
  Returns all films.
  """
  getFilms(filter: String): FilmsCollection @cacheControl(maxAge: 240)
}