# import * from './parts/film.gql'

enum CacheControlScope {
    PUBLIC
    PRIVATE
  }

directive @cacheControl(
    maxAge: Int
    scope: CacheControlScope
    inheritMaxAge: Boolean
  ) on FIELD_DEFINITION | OBJECT | INTERFACE | UNION

type SpeciesCollection {
  items: [Specie]!
  total: Int!
}

type FilmsCollection {
    items: [Film]!
    total: Int!
}

type VehiclesCollection {
    items: [Vehicle]!
    total: Int!
}

type Specie @cacheControl(maxAge: 86400){
  name: String!
  classification: String!
  designation: String!
  average_height: String!
  skin_colors: String!
  eye_colors: String!
  hair_colors: String!
  homeworld: String!
  language: String!
  people: [String]!
  films: [String]!
  created: String!
  edited: String!
  url: String!
}

type Film @cacheControl(maxAge: 86400){
  title: String!
  episode_id: String!
  opening_crawl: String!
  director: String!
  producer: String!
  release_date: String!
  characters: [String]!
  planets: [String]!
  starships: [String]!
  vehicles: [String]!
  species: [String]!
  created: String!
  edited: String!
  url: String!
}

type Vehicle @cacheControl(maxAge: 86400) {
  name: String!
  model: String!
  vehicle_class: String!
  manufacturer: String!
  length: String!
  cost_in_credits: String!
  crew: String!
  passengers: String!
  max_atmosphering_speed: String!
  cargo_capacity: String!
  consumables: String
  films: [String!]!
  pilots: [String!]!
  url: String!
  created: String!
  edited: String!
}

type Query {
  """
  Returns all films.
  """
  getFilms(filter: String): FilmsCollection @cacheControl(maxAge: 86400)
  """
  Returns all species.
  """
  getSpecies(filter: String): SpeciesCollection @cacheControl(maxAge: 86400)
  """
  Returns all vehicles.
  """
  getVehicles(filter: String): VehiclesCollection @cacheControl(maxAge: 86400)
}